COMPILER = g++

compile:
	$(COMPILER) main.cpp -o zycamera-launcher/usr/bin/zycamera-launcher
	$(COMPILER) main.cpp -o init

clean:
	sudo rm -rf zycamera-launcher/usr/bin/zycamera-launcher
	sudo rm -rf init
